server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

raycast:
  xray: "/path/to/xray"
  xrayConfig: "/tmp/raycast-config.json"
  xrayApiSocket: "/tmp/raycast-socket.sock"

panel:
  enabled: true
  webEnabled: true
  apiEnabled: true
  rootDir: "/_p"


# {
#   "inbounds": [
#     {
#       "listen": "127.0.0.1",
#       "port": 1080,
#       "protocol": "协议名称",
#       "settings": {},
#       "streamSettings": {},
#       "tag": "标识",
#       "sniffing": {
#         "enabled": true,
#         "destOverride": ["http", "tls"]
#       },
#       "allocate": {
#         "strategy": "always",
#         "refresh": 5,
#         "concurrency": 3
#       }
#     }
#   ]
# }


# {
#   "clients": [
#     {
#       "id": "5783a3e7-e373-51cd-8642-c83782b807c5",
#       "level": 0,
#       "alterId": 0,
#       "email": "love@xray.com"
#     }
#   ],
#   "default": {
#     "level": 0,
#     "alterId": 0
#   },
#   "detour": {
#     "to": "tag_to_detour"
#   },
#   "disableInsecureEncryption": false
# }

certificates:
  - c1:
    refresh: 3600
    cert: "/path/to/cert.crt"
    key: "/path/to/key.key"

inbound:
  - vmess:
      listen: "127.0.0.1:1081"
      users:
        - "de09c259-2132-4ba5-b922-f9e80edcd4e0,u1"
        - "117ca23b-40ba-426b-94b9-4b8dc97f3383,u2"
      security:
        reality: "quq.example.com,bnb.example.com"
        priKey: "KLjeBJPS6QM9C5QzF1Deun7O6lUgysNOS4u0ppAppFQ"
        pubKey: "Fscob0tMI2OZ7pRV22z8Kqnt6oW-HcoBS9KlwYJQkwY"
        secret:
          - "1234567890qwerty"
          - "0987654321poiuyt"
        fingerprint: "firefox"
        fallback: "127.0.0.1:443|0"
        ver: "1.8.0,1.8.1"
        timeDiff: 100

  - vmess:
      listen: "127.0.0.1:1080"
      users:
        - "4b15c15e-5cc4-459f-aa09-63ec873e0c11,u3"
        - "48c1751a-f5c9-4d93-a27a-e3cff1c92b6c,u4"
      security:
        tls: "1.2-1.3"
        domain: "www.example.com"
        sniCheck: true
        alpn: "h2,http/1.1"
        cipherSuites: ""
        fingerprint: "firefox"
        certificates: "c1"


outbound:
  - subscribe:
      link: "https://example.com/sub"
      refresh: 3600
